# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s13core.content_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to allow the system to auto-generate.', unique=True)),
                ('title', models.CharField(help_text="HTML compliance is recommended; i.e. use &amp;amp; for &amp;'s.", max_length=255, null=True)),
                ('body', models.TextField(blank=True, help_text='Usually HTML but may vary depending on the template. May also contain Jinja2 code.', null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('date_made', models.DateTimeField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True, null=True)),
                ('sort_article_media', models.CharField(blank=True, choices=[('title', 'Title Ascending'), ('-title', 'Title Descending'), ('alt_text', 'Alt Text Ascending'), ('-alt_text', 'Alt Text Descending')], default='title', help_text='Sorting strategy for media associated with this article.', max_length=128)),
                ('template', models.CharField(blank=True, choices=[['admin/sidebars/nav_fileassets.html', 'admin/sidebars/nav_fileassets.html'], ['admin/sidebars/nav_settings.html', 'admin/sidebars/nav_settings.html'], ['admin/sidebars/nav_articles.html', 'admin/sidebars/nav_articles.html'], ['admin/forms/update_settings.html', 'admin/forms/update_settings.html'], ['admin/forms/update_fileasset.html', 'admin/forms/update_fileasset.html'], ['admin/forms/update_article.html', 'admin/forms/update_article.html'], ['admin/forms/generic.html', 'admin/forms/generic.html']], max_length=255, null=True)),
                ('js', models.TextField(blank=True, help_text='Custom JavaScript for this article.', null=True, verbose_name='JavaScript')),
                ('css', models.TextField(blank=True, help_text='Custom Cascading Style Sheet for this article.', null=True, verbose_name='Custom CSS')),
                ('is_public', models.BooleanField(default=True, help_text='Make this article available to your viewers.')),
                ('is_homepage', models.BooleanField(default=False, help_text="Make this article the website's homepage.")),
                ('sort_children', models.CharField(blank=True, choices=[('pk', 'Date Made (Oldest First)'), ('-pk', 'Date Made (Newest First)'), ('date_edit', 'Edit Date (Freshest First)'), ('-date_edit', 'Edit Date (Freshest Last)'), ('title', 'Title (Alphabetical)'), ('-title', 'Title (Reverse Alphabetical)'), ('weight', 'Weight (Ascending)'), ('-weight', 'Weight (Descending)')], default='-pk', help_text='Sorting strategy for child articles when generating<br />navigation links and other user interfaces.', max_length=255)),
                ('include_children', models.IntegerField(blank=True, default=0, help_text='Number of child articles to include in a page;<br />i.e., a Paginator instance.')),
                ('weight', models.IntegerField(blank=True, default=0, help_text='Use this field as an alternate sorting value.')),
            ],
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(blank=True, default=None, storage=s13core.content_management.models.OverwriteStorage(), upload_to='')),
                ('extension', models.CharField(blank=True, default='', max_length=8)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Value used for alt attributes in images and other elements.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'File Asset',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Associate an image with this article.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_image', to='content_management.FileAsset'),
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='Associate file assets like photos to this article.', related_name='article_media', to='content_management.FileAsset'),
        ),
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Assiciate this article as a child of another article.', null=True, on_delete=django.db.models.deletion.CASCADE, to='content_management.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='sidelinks',
            field=models.ManyToManyField(blank=True, related_name='side_links', to='content_management.Article'),
        ),
    ]
