# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_auto_20170523_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='template',
            field=models.CharField(blank=True, choices=[['admin/sidebars/nav_fileassets.html', 'admin/sidebars/nav_fileassets.html'], ['admin/sidebars/nav_settings.html', 'admin/sidebars/nav_settings.html'], ['admin/sidebars/nav_articles.html', 'admin/sidebars/nav_articles.html'], ['admin/forms/update_settings.html', 'admin/forms/update_settings.html'], ['admin/forms/update_fileasset.html', 'admin/forms/update_fileasset.html'], ['admin/forms/update_article.html', 'admin/forms/update_article.html'], ['admin/forms/generic.html', 'admin/forms/generic.html']], max_length=255, null=True),
        ),
    ]
