# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_auto_20170524_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
