# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_auto_20170524_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='date_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
