# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_auto_20180317_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='limit_media',
            field=models.IntegerField(blank=True, default=0, help_text='Limit the number of associated media to display;<br />a value of zero will show all associated media.', verbose_name='Article Media Limit'),
        ),
        migrations.AlterField(
            model_name='article',
            name='include_children',
            field=models.IntegerField(blank=True, default=0, help_text='Number of child articles to include in a page;<br />i.e., a Paginator instance.', verbose_name='Include Children'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_homepage',
            field=models.BooleanField(default=False, help_text="Make this article the website's homepage.", verbose_name='Is Homepage'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Make this article available to your viewers.', verbose_name='Is Public'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sort_article_media',
            field=models.CharField(blank=True, choices=[('pk', 'Date Made (Oldest First)'), ('-pk', 'Date Made (Newest First)'), ('title', 'Title Ascending'), ('-title', 'Title Descending'), ('date_edit', 'Edit Date (Freshest First)'), ('-date_edit', 'Edit Date (Freshest Last)')], default='title', help_text='Sorting strategy for media associated with this article.', max_length=128, verbose_name='Sort Article Media'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sort_children',
            field=models.CharField(blank=True, choices=[('pk', 'Date Made (Oldest First)'), ('-pk', 'Date Made (Newest First)'), ('date_edit', 'Edit Date (Freshest First)'), ('-date_edit', 'Edit Date (Freshest Last)'), ('title', 'Title (Alphabetical)'), ('-title', 'Title (Reverse Alphabetical)'), ('weight', 'Weight (Ascending)'), ('-weight', 'Weight (Descending)')], default='-pk', help_text='Sorting strategy for child articles when generating<br />navigation links and other user interfaces.', max_length=255, verbose_name='Sort Children'),
        ),
    ]
