# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_fileasset_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
