# Generated by Django 3.2.8 on 2021-10-10 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_management', '0009_auto_20180323_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Associate an image with this article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_image', to='content_management.fileasset'),
        ),
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Assiciate this article as a child of another article.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.article'),
        ),
    ]
