# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_management', '0005_auto_20170524_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocMedFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, unique=True)),
                ('account_id', models.CharField(max_length=64)),
                ('max_results', models.IntegerField(default=5)),
                ('response', models.TextField()),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socmed_collector.APIKey')),
                ('cms_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocMedProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, unique=True)),
                ('uri', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('notes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='socmedfeed',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socmed_collector.SocMedProcessor'),
        ),
    ]
