# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API Key'},
        ),
        migrations.AlterModelOptions(
            name='socmedfeed',
            options={'verbose_name': 'Social Media Feed'},
        ),
        migrations.AlterModelOptions(
            name='socmedprocessor',
            options={'verbose_name': 'Social Media Feed Processor'},
        ),
        migrations.AlterField(
            model_name='socmedprocessor',
            name='code',
            field=models.TextField(verbose_name='Python Code'),
        ),
        migrations.AlterField(
            model_name='socmedprocessor',
            name='uri',
            field=models.CharField(max_length=255, verbose_name='API Endpoint URI'),
        ),
    ]
