# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_collector', '0002_auto_20180313_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socmedfeed',
            name='account_id',
            field=models.CharField(max_length=64, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='socmedfeed',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socmed_collector.APIKey', verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='socmedfeed',
            name='cms_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.Article', verbose_name='Target Website Section'),
        ),
        migrations.AlterField(
            model_name='socmedfeed',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socmed_collector.SocMedProcessor', verbose_name='Feed Processor'),
        ),
        migrations.AlterField(
            model_name='socmedfeed',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
