# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_collector', '0003_auto_20180313_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socmedfeed',
            name='cms_section',
        ),
    ]
