# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=128)),
                ('sender_email', models.EmailField(max_length=254)),
                ('message_body', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
