# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 01:20
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(app, schema_editor):
    QuestionAnswerPair = app.get_model('messaging', 'QuestionAnswerPair')
    db_alias = schema_editor.connection.alias
    QuestionAnswerPair.objects.using(db_alias).bulk_create([
        QuestionAnswerPair(question='1 + 1', answer='2'),
        QuestionAnswerPair(question='8 + 8', answer='16'),
    ])


def reverse_func(app, schema_editor):
    QuestionAnswerPair = app.get_model('messaging', 'QuestionAnswerPair')
    db_alias = schema_editor.connection.alias
    for qa in QuestionAnswerPair.objects.all():
        QuestionAnswerPair.objects.user(db_alias).filter(pk=qa.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20180523_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerPair',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('question', models.CharField(max_length=128)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
