# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(default='Juan de la Cruz', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Physical address. HTML allowed.', null=True)),
                ('email', models.CharField(blank=True, help_text='Comma-separated email addresses.', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Comma-separated phone numbers.', max_length=255, null=True)),
                ('weight', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'ordering': ['weight', 'contact_name'],
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='CopyrightInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(default='', help_text='Usually appears at the footer of a webpage, like:<br />Copyright &copy; 2016. Your Company Name. All rights reserved.', max_length=255, verbose_name='Copyright Statement')),
                ('license', models.CharField(blank=True, help_text='Content licensing reference title, like:<br />Creative Commons Attribution Share-Alike International License', max_length=255, null=True, verbose_name='Content License')),
                ('link', models.CharField(blank=True, help_text='Link to the full content license text, if any.<br />https://creativecommons.org/licenses/by-sa/4.0/legalcode', max_length=255, null=True, verbose_name='Link to License')),
            ],
            options={
                'verbose_name': 'Copyright Information',
                'ordering': ['statement'],
                'verbose_name_plural': 'Copyright Information',
            },
        ),
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Disclaimer', max_length=255)),
                ('body', models.TextField(default='', help_text='HTML allowed.')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Unique name for this setting.', max_length=128, unique=True, verbose_name='Setting Name')),
                ('title', models.CharField(default='My S13Core Website', help_text='Overall title of the website.', max_length=128, verbose_name='Website Title')),
                ('description', models.CharField(blank=True, help_text='General overview for the website. Used when an article has a blank description field.', max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Keywords associated with the whole website.', max_length=255, null=True)),
                ('append_keywords', models.BooleanField(default=True, help_text='Always append the website keywords to meta information?')),
                ('nohome_content_type', models.CharField(blank=True, choices=[('sections', 'Show the website sections'), ('articles', 'Show the latest articles'), ('custom_html', 'Show a custom html'), ('none', 'Show nothing')], default='none', help_text='Show these contents when there is no selected homepage.', max_length=12, verbose_name='Show Contents')),
                ('nohome_content_items', models.IntegerField(blank=True, default=8, help_text='Number of items to show, if any.', verbose_name='Items')),
                ('nohome_title', models.CharField(blank=True, help_text='Use this title instead of “Website Under Construction”', max_length=128, null=True, verbose_name='Alternate Title')),
                ('nohome_custom', models.TextField(blank=True, help_text='HTML code for when “custom page” is selected.', verbose_name='Custom HTML')),
                ('css', models.TextField(blank=True, help_text='Link elements to stylesheets and/or style elements with inline CSS definitions, like:<br />&lt;link rel="stylesheet" href="/static/css/default.css" /&gt;', null=True, verbose_name='Stylesheets')),
                ('js', models.TextField(blank=True, help_text='Script elements with sources or inline JavaScript code, like:<br />&lt;script src="/static/js/test.js"&gt;&lt;/script&gt;', null=True, verbose_name='JavaScripts')),
                ('contact', models.ManyToManyField(blank=True, to='settings.ContactInfo', verbose_name='Contact Information')),
                ('copyright', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.CopyrightInfo', verbose_name='Copyright Infomration')),
                ('disclaimer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Disclaimer')),
            ],
            options={
                'ordering': ['-is_active', 'title'],
            },
        ),
    ]
