# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='keywords_search_items',
            field=models.IntegerField(blank=True, default=12, help_text='Number of search results to show per page, if any.', verbose_name='Search Results Items'),
        ),
    ]
