# Generated by Django 3.2.8 on 2021-10-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_keywords_search_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='copyright',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.copyrightinfo', verbose_name='Copyright Infomration'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='disclaimer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.disclaimer'),
        ),
    ]
